// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetProjectsRequest_OrderBy int32

const (
	GetProjectsRequest_NAME          GetProjectsRequest_OrderBy = 0
	GetProjectsRequest_CREATION_DATE GetProjectsRequest_OrderBy = 1
	GetProjectsRequest_ISSUES_COUNT  GetProjectsRequest_OrderBy = 2
)

var GetProjectsRequest_OrderBy_name = map[int32]string{
	0: "NAME",
	1: "CREATION_DATE",
	2: "ISSUES_COUNT",
}

var GetProjectsRequest_OrderBy_value = map[string]int32{
	"NAME":          0,
	"CREATION_DATE": 1,
	"ISSUES_COUNT":  2,
}

func (x GetProjectsRequest_OrderBy) String() string {
	return proto.EnumName(GetProjectsRequest_OrderBy_name, int32(x))
}

func (GetProjectsRequest_OrderBy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0, 0}
}

type GetProjectsRequest_OrderDirection int32

const (
	GetProjectsRequest_ASC  GetProjectsRequest_OrderDirection = 0
	GetProjectsRequest_DESC GetProjectsRequest_OrderDirection = 1
)

var GetProjectsRequest_OrderDirection_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}

var GetProjectsRequest_OrderDirection_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x GetProjectsRequest_OrderDirection) String() string {
	return proto.EnumName(GetProjectsRequest_OrderDirection_name, int32(x))
}

func (GetProjectsRequest_OrderDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0, 1}
}

type GetProjectsRequest struct {
	OrderBy              GetProjectsRequest_OrderBy        `protobuf:"varint,1,opt,name=order_by,json=orderBy,proto3,enum=GetProjectsRequest_OrderBy" json:"order_by,omitempty"`
	OrderDir             GetProjectsRequest_OrderDirection `protobuf:"varint,2,opt,name=order_dir,json=orderDir,proto3,enum=GetProjectsRequest_OrderDirection" json:"order_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *GetProjectsRequest) Reset()         { *m = GetProjectsRequest{} }
func (m *GetProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectsRequest) ProtoMessage()    {}
func (*GetProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *GetProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectsRequest.Unmarshal(m, b)
}
func (m *GetProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectsRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectsRequest.Merge(m, src)
}
func (m *GetProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectsRequest.Size(m)
}
func (m *GetProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectsRequest proto.InternalMessageInfo

func (m *GetProjectsRequest) GetOrderBy() GetProjectsRequest_OrderBy {
	if m != nil {
		return m.OrderBy
	}
	return GetProjectsRequest_NAME
}

func (m *GetProjectsRequest) GetOrderDir() GetProjectsRequest_OrderDirection {
	if m != nil {
		return m.OrderDir
	}
	return GetProjectsRequest_ASC
}

type ProjectsListResponse struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	Total                int32      `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProjectsListResponse) Reset()         { *m = ProjectsListResponse{} }
func (m *ProjectsListResponse) String() string { return proto.CompactTextString(m) }
func (*ProjectsListResponse) ProtoMessage()    {}
func (*ProjectsListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *ProjectsListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectsListResponse.Unmarshal(m, b)
}
func (m *ProjectsListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectsListResponse.Marshal(b, m, deterministic)
}
func (m *ProjectsListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectsListResponse.Merge(m, src)
}
func (m *ProjectsListResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectsListResponse.Size(m)
}
func (m *ProjectsListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectsListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectsListResponse proto.InternalMessageInfo

func (m *ProjectsListResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

func (m *ProjectsListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type CreateProjectRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rules                []*Rule  `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(m, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProjectRequest) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

type CreateProjectResponse struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectResponse) Reset()         { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()    {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *CreateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectResponse.Unmarshal(m, b)
}
func (m *CreateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectResponse.Marshal(b, m, deterministic)
}
func (m *CreateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectResponse.Merge(m, src)
}
func (m *CreateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProjectResponse.Size(m)
}
func (m *CreateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectResponse proto.InternalMessageInfo

func (m *CreateProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type GetProjectRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectRequest) Reset()         { *m = GetProjectRequest{} }
func (m *GetProjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectRequest) ProtoMessage()    {}
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *GetProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectRequest.Unmarshal(m, b)
}
func (m *GetProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectRequest.Merge(m, src)
}
func (m *GetProjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectRequest.Size(m)
}
func (m *GetProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectRequest proto.InternalMessageInfo

func (m *GetProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ProjectResponse struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectResponse) Reset()         { *m = ProjectResponse{} }
func (m *ProjectResponse) String() string { return proto.CompactTextString(m) }
func (*ProjectResponse) ProtoMessage()    {}
func (*ProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *ProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectResponse.Unmarshal(m, b)
}
func (m *ProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectResponse.Marshal(b, m, deterministic)
}
func (m *ProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectResponse.Merge(m, src)
}
func (m *ProjectResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectResponse.Size(m)
}
func (m *ProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectResponse proto.InternalMessageInfo

func (m *ProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type Project struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rules                []*Rule  `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	CreatedAt            int64    `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IssuesCount          int32    `protobuf:"varint,4,opt,name=issues_count,json=issuesCount,proto3" json:"issues_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *Project) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Project) GetIssuesCount() int32 {
	if m != nil {
		return m.IssuesCount
	}
	return 0
}

type Rule struct {
	MinAge               int32    `protobuf:"varint,1,opt,name=min_age,json=minAge,proto3" json:"min_age,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (m *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(m, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetMinAge() int32 {
	if m != nil {
		return m.MinAge
	}
	return 0
}

func (m *Rule) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterEnum("GetProjectsRequest_OrderBy", GetProjectsRequest_OrderBy_name, GetProjectsRequest_OrderBy_value)
	proto.RegisterEnum("GetProjectsRequest_OrderDirection", GetProjectsRequest_OrderDirection_name, GetProjectsRequest_OrderDirection_value)
	proto.RegisterType((*GetProjectsRequest)(nil), "GetProjectsRequest")
	proto.RegisterType((*ProjectsListResponse)(nil), "ProjectsListResponse")
	proto.RegisterType((*CreateProjectRequest)(nil), "CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "CreateProjectResponse")
	proto.RegisterType((*GetProjectRequest)(nil), "GetProjectRequest")
	proto.RegisterType((*ProjectResponse)(nil), "ProjectResponse")
	proto.RegisterType((*Project)(nil), "Project")
	proto.RegisterType((*Rule)(nil), "Rule")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x9b, 0xb8, 0x76, 0x26, 0x6d, 0x71, 0x87, 0x04, 0xac, 0x54, 0x48, 0x61, 0x41, 0x22,
	0xa7, 0x3d, 0x04, 0x15, 0x81, 0x90, 0x40, 0x8e, 0x63, 0x55, 0x95, 0x20, 0x41, 0xeb, 0xf4, 0xc2,
	0xc5, 0x72, 0x9d, 0x55, 0xb5, 0x90, 0xd8, 0x66, 0xbd, 0x3e, 0x54, 0xe2, 0x8f, 0xf1, 0x9f, 0xf8,
	0x11, 0xc8, 0x6b, 0x87, 0x7e, 0x05, 0x24, 0x38, 0x79, 0xf7, 0xed, 0xcc, 0x9b, 0x37, 0x6f, 0xc6,
	0xd0, 0x89, 0x73, 0x41, 0x73, 0x99, 0xa9, 0x8c, 0xfc, 0x34, 0x00, 0x4f, 0xb9, 0xfa, 0x24, 0xb3,
	0x2f, 0x3c, 0x51, 0x05, 0xe3, 0xdf, 0x4a, 0x5e, 0x28, 0x7c, 0x05, 0x76, 0x26, 0x97, 0x5c, 0x46,
	0x17, 0x57, 0xae, 0x31, 0x34, 0x46, 0x87, 0xe3, 0x63, 0x7a, 0x3f, 0x8c, 0xce, 0xab, 0x98, 0xc9,
	0x15, 0xb3, 0xb2, 0xfa, 0x80, 0xef, 0xa1, 0x53, 0xe7, 0x2d, 0x85, 0x74, 0x77, 0x75, 0x22, 0xf9,
	0x63, 0xe2, 0x54, 0x48, 0x9e, 0x28, 0x91, 0xa5, 0xac, 0x2e, 0x36, 0x15, 0x92, 0xbc, 0x06, 0xab,
	0x21, 0x45, 0x1b, 0xda, 0x33, 0xef, 0x63, 0xe0, 0xec, 0xe0, 0x11, 0x1c, 0xf8, 0x2c, 0xf0, 0x16,
	0x67, 0xf3, 0x59, 0x34, 0xf5, 0x16, 0x81, 0x63, 0xa0, 0x03, 0xfb, 0x67, 0x61, 0x78, 0x1e, 0x84,
	0x91, 0x3f, 0x3f, 0x9f, 0x2d, 0x9c, 0x5d, 0xf2, 0x0c, 0x0e, 0x6f, 0xb3, 0xa2, 0x05, 0x2d, 0x2f,
	0xf4, 0x9d, 0x9d, 0x8a, 0x69, 0x1a, 0x84, 0xbe, 0x63, 0x10, 0x06, 0xbd, 0x8d, 0x94, 0x0f, 0xa2,
	0x50, 0x8c, 0x17, 0x79, 0x96, 0x16, 0x1c, 0x9f, 0x83, 0x9d, 0x37, 0xb8, 0x6b, 0x0c, 0x5b, 0xa3,
	0xee, 0xd8, 0xa6, 0x4d, 0x20, 0xfb, 0xfd, 0x82, 0x3d, 0x30, 0x55, 0xa6, 0xe2, 0x95, 0xee, 0xcc,
	0x64, 0xf5, 0x85, 0x9c, 0x42, 0xcf, 0x97, 0x3c, 0x56, 0x7c, 0x93, 0xd0, 0x78, 0x88, 0xd0, 0x4e,
	0xe3, 0x35, 0xd7, 0xfe, 0x75, 0x98, 0x3e, 0xe3, 0x31, 0x98, 0xb2, 0x5c, 0xf1, 0xc2, 0xdd, 0xd5,
	0x45, 0x4c, 0xca, 0xca, 0x15, 0x67, 0x35, 0x46, 0xde, 0x42, 0xff, 0x0e, 0x51, 0xa3, 0x8e, 0x80,
	0xd5, 0x68, 0xd0, 0x64, 0x37, 0xc5, 0x6d, 0x1e, 0xc8, 0x0b, 0x38, 0xba, 0xf6, 0xf9, 0x2f, 0x12,
	0xc8, 0x09, 0x3c, 0xf8, 0x1f, 0xfe, 0xef, 0x60, 0x35, 0xd8, 0x3f, 0x37, 0x86, 0x4f, 0x00, 0x12,
	0xdd, 0xd8, 0x32, 0x8a, 0x95, 0xdb, 0x1a, 0x1a, 0xa3, 0x16, 0xeb, 0x34, 0x88, 0xa7, 0xf0, 0x29,
	0xec, 0x8b, 0xa2, 0x28, 0x79, 0x11, 0x25, 0x59, 0x99, 0x2a, 0xb7, 0xad, 0xdd, 0xed, 0xd6, 0x98,
	0x5f, 0x41, 0xe4, 0x04, 0xda, 0x15, 0x21, 0x3e, 0x06, 0x6b, 0x2d, 0xd2, 0x28, 0xbe, 0xac, 0xab,
	0x9b, 0x6c, 0x6f, 0x2d, 0x52, 0xef, 0x92, 0x57, 0xa3, 0xa9, 0x93, 0x9b, 0xd1, 0xe8, 0xcb, 0xf8,
	0x87, 0x01, 0xf6, 0x24, 0x4e, 0xbe, 0x4a, 0x2f, 0x17, 0xf8, 0x06, 0xba, 0x37, 0x36, 0x11, 0x1f,
	0x6e, 0xd9, 0xcb, 0x41, 0x9f, 0x6e, 0x5d, 0x8f, 0x31, 0xc0, 0x75, 0x30, 0x22, 0xbd, 0xe7, 0xf4,
	0xc0, 0xa1, 0x77, 0x4d, 0x7d, 0x07, 0x07, 0xb7, 0xa6, 0x89, 0x7d, 0xba, 0x6d, 0x4d, 0x06, 0x8f,
	0xe8, 0xd6, 0xa1, 0x4f, 0xac, 0xcf, 0xa6, 0xfe, 0x45, 0x2f, 0xf6, 0xf4, 0xe7, 0xe5, 0xaf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb1, 0x58, 0x04, 0x57, 0xb6, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BackrApiClient is the client API for BackrApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BackrApiClient interface {
	GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*ProjectsListResponse, error)
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
}

type backrApiClient struct {
	cc *grpc.ClientConn
}

func NewBackrApiClient(cc *grpc.ClientConn) BackrApiClient {
	return &backrApiClient{cc}
}

func (c *backrApiClient) GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*ProjectsListResponse, error) {
	out := new(ProjectsListResponse)
	err := c.cc.Invoke(ctx, "/BackrApi/GetProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backrApiClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	out := new(ProjectResponse)
	err := c.cc.Invoke(ctx, "/BackrApi/GetProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backrApiClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	out := new(CreateProjectResponse)
	err := c.cc.Invoke(ctx, "/BackrApi/CreateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackrApiServer is the server API for BackrApi service.
type BackrApiServer interface {
	GetProjects(context.Context, *GetProjectsRequest) (*ProjectsListResponse, error)
	GetProject(context.Context, *GetProjectRequest) (*ProjectResponse, error)
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
}

// UnimplementedBackrApiServer can be embedded to have forward compatible implementations.
type UnimplementedBackrApiServer struct {
}

func (*UnimplementedBackrApiServer) GetProjects(ctx context.Context, req *GetProjectsRequest) (*ProjectsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjects not implemented")
}
func (*UnimplementedBackrApiServer) GetProject(ctx context.Context, req *GetProjectRequest) (*ProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProject not implemented")
}
func (*UnimplementedBackrApiServer) CreateProject(ctx context.Context, req *CreateProjectRequest) (*CreateProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}

func RegisterBackrApiServer(s *grpc.Server, srv BackrApiServer) {
	s.RegisterService(&_BackrApi_serviceDesc, srv)
}

func _BackrApi_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackrApiServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackrApi/GetProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackrApiServer).GetProjects(ctx, req.(*GetProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackrApi_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackrApiServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackrApi/GetProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackrApiServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackrApi_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackrApiServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackrApi/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackrApiServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BackrApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BackrApi",
	HandlerType: (*BackrApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProjects",
			Handler:    _BackrApi_GetProjects_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _BackrApi_GetProject_Handler,
		},
		{
			MethodName: "CreateProject",
			Handler:    _BackrApi_CreateProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
