// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error int32

const (
	Error_NO_ERROR  Error = 0
	Error_UNKNOWN   Error = 1
	Error_OBSOLETE  Error = 2
	Error_TOO_SMALL Error = 3
	Error_NO_FILE   Error = 4
)

var Error_name = map[int32]string{
	0: "NO_ERROR",
	1: "UNKNOWN",
	2: "OBSOLETE",
	3: "TOO_SMALL",
	4: "NO_FILE",
}

var Error_value = map[string]int32{
	"NO_ERROR":  0,
	"UNKNOWN":   1,
	"OBSOLETE":  2,
	"TOO_SMALL": 3,
	"NO_FILE":   4,
}

func (x Error) String() string {
	return proto.EnumName(Error_name, int32(x))
}

func (Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type GetProjectsRequest_OrderBy int32

const (
	GetProjectsRequest_NAME          GetProjectsRequest_OrderBy = 0
	GetProjectsRequest_CREATION_DATE GetProjectsRequest_OrderBy = 1
	GetProjectsRequest_ISSUES_COUNT  GetProjectsRequest_OrderBy = 2
)

var GetProjectsRequest_OrderBy_name = map[int32]string{
	0: "NAME",
	1: "CREATION_DATE",
	2: "ISSUES_COUNT",
}

var GetProjectsRequest_OrderBy_value = map[string]int32{
	"NAME":          0,
	"CREATION_DATE": 1,
	"ISSUES_COUNT":  2,
}

func (x GetProjectsRequest_OrderBy) String() string {
	return proto.EnumName(GetProjectsRequest_OrderBy_name, int32(x))
}

func (GetProjectsRequest_OrderBy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0, 0}
}

type GetProjectsRequest_OrderDirection int32

const (
	GetProjectsRequest_ASC  GetProjectsRequest_OrderDirection = 0
	GetProjectsRequest_DESC GetProjectsRequest_OrderDirection = 1
)

var GetProjectsRequest_OrderDirection_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}

var GetProjectsRequest_OrderDirection_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x GetProjectsRequest_OrderDirection) String() string {
	return proto.EnumName(GetProjectsRequest_OrderDirection_name, int32(x))
}

func (GetProjectsRequest_OrderDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0, 1}
}

type GetProjectsRequest struct {
	OrderBy              GetProjectsRequest_OrderBy        `protobuf:"varint,1,opt,name=order_by,json=orderBy,proto3,enum=GetProjectsRequest_OrderBy" json:"order_by,omitempty"`
	OrderDir             GetProjectsRequest_OrderDirection `protobuf:"varint,2,opt,name=order_dir,json=orderDir,proto3,enum=GetProjectsRequest_OrderDirection" json:"order_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *GetProjectsRequest) Reset()         { *m = GetProjectsRequest{} }
func (m *GetProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectsRequest) ProtoMessage()    {}
func (*GetProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *GetProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectsRequest.Unmarshal(m, b)
}
func (m *GetProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectsRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectsRequest.Merge(m, src)
}
func (m *GetProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectsRequest.Size(m)
}
func (m *GetProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectsRequest proto.InternalMessageInfo

func (m *GetProjectsRequest) GetOrderBy() GetProjectsRequest_OrderBy {
	if m != nil {
		return m.OrderBy
	}
	return GetProjectsRequest_NAME
}

func (m *GetProjectsRequest) GetOrderDir() GetProjectsRequest_OrderDirection {
	if m != nil {
		return m.OrderDir
	}
	return GetProjectsRequest_ASC
}

type ProjectsListResponse struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	Total                int32      `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProjectsListResponse) Reset()         { *m = ProjectsListResponse{} }
func (m *ProjectsListResponse) String() string { return proto.CompactTextString(m) }
func (*ProjectsListResponse) ProtoMessage()    {}
func (*ProjectsListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *ProjectsListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectsListResponse.Unmarshal(m, b)
}
func (m *ProjectsListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectsListResponse.Marshal(b, m, deterministic)
}
func (m *ProjectsListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectsListResponse.Merge(m, src)
}
func (m *ProjectsListResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectsListResponse.Size(m)
}
func (m *ProjectsListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectsListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectsListResponse proto.InternalMessageInfo

func (m *ProjectsListResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

func (m *ProjectsListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type CreateProjectRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rules                []*Rule  `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(m, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProjectRequest) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

type CreateProjectResponse struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectResponse) Reset()         { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()    {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *CreateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectResponse.Unmarshal(m, b)
}
func (m *CreateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectResponse.Marshal(b, m, deterministic)
}
func (m *CreateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectResponse.Merge(m, src)
}
func (m *CreateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProjectResponse.Size(m)
}
func (m *CreateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectResponse proto.InternalMessageInfo

func (m *CreateProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type GetProjectRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectRequest) Reset()         { *m = GetProjectRequest{} }
func (m *GetProjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectRequest) ProtoMessage()    {}
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *GetProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectRequest.Unmarshal(m, b)
}
func (m *GetProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectRequest.Merge(m, src)
}
func (m *GetProjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectRequest.Size(m)
}
func (m *GetProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectRequest proto.InternalMessageInfo

func (m *GetProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ProjectResponse struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectResponse) Reset()         { *m = ProjectResponse{} }
func (m *ProjectResponse) String() string { return proto.CompactTextString(m) }
func (*ProjectResponse) ProtoMessage()    {}
func (*ProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *ProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectResponse.Unmarshal(m, b)
}
func (m *ProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectResponse.Marshal(b, m, deterministic)
}
func (m *ProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectResponse.Merge(m, src)
}
func (m *ProjectResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectResponse.Size(m)
}
func (m *ProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectResponse proto.InternalMessageInfo

func (m *ProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type GetFilesRequest struct {
	ProjectName          string   `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFilesRequest) Reset()         { *m = GetFilesRequest{} }
func (m *GetFilesRequest) String() string { return proto.CompactTextString(m) }
func (*GetFilesRequest) ProtoMessage()    {}
func (*GetFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *GetFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFilesRequest.Unmarshal(m, b)
}
func (m *GetFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFilesRequest.Marshal(b, m, deterministic)
}
func (m *GetFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFilesRequest.Merge(m, src)
}
func (m *GetFilesRequest) XXX_Size() int {
	return xxx_messageInfo_GetFilesRequest.Size(m)
}
func (m *GetFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFilesRequest proto.InternalMessageInfo

func (m *GetFilesRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *GetFilesRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetFilesResponse struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFilesResponse) Reset()         { *m = GetFilesResponse{} }
func (m *GetFilesResponse) String() string { return proto.CompactTextString(m) }
func (*GetFilesResponse) ProtoMessage()    {}
func (*GetFilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *GetFilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFilesResponse.Unmarshal(m, b)
}
func (m *GetFilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFilesResponse.Marshal(b, m, deterministic)
}
func (m *GetFilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFilesResponse.Merge(m, src)
}
func (m *GetFilesResponse) XXX_Size() int {
	return xxx_messageInfo_GetFilesResponse.Size(m)
}
func (m *GetFilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFilesResponse proto.InternalMessageInfo

func (m *GetFilesResponse) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type GetFileURLRequest struct {
	Filepath             string   `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileURLRequest) Reset()         { *m = GetFileURLRequest{} }
func (m *GetFileURLRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileURLRequest) ProtoMessage()    {}
func (*GetFileURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *GetFileURLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileURLRequest.Unmarshal(m, b)
}
func (m *GetFileURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileURLRequest.Marshal(b, m, deterministic)
}
func (m *GetFileURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileURLRequest.Merge(m, src)
}
func (m *GetFileURLRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileURLRequest.Size(m)
}
func (m *GetFileURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileURLRequest proto.InternalMessageInfo

func (m *GetFileURLRequest) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

type GetFileURLResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileURLResponse) Reset()         { *m = GetFileURLResponse{} }
func (m *GetFileURLResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileURLResponse) ProtoMessage()    {}
func (*GetFileURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *GetFileURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileURLResponse.Unmarshal(m, b)
}
func (m *GetFileURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileURLResponse.Marshal(b, m, deterministic)
}
func (m *GetFileURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileURLResponse.Merge(m, src)
}
func (m *GetFileURLResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileURLResponse.Size(m)
}
func (m *GetFileURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileURLResponse proto.InternalMessageInfo

func (m *GetFileURLResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type CreateAccountRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type AccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountResponse) Reset()         { *m = AccountResponse{} }
func (m *AccountResponse) String() string { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()    {}
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *AccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResponse.Unmarshal(m, b)
}
func (m *AccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResponse.Marshal(b, m, deterministic)
}
func (m *AccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResponse.Merge(m, src)
}
func (m *AccountResponse) XXX_Size() int {
	return xxx_messageInfo_AccountResponse.Size(m)
}
func (m *AccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResponse proto.InternalMessageInfo

func (m *AccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *AccountResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ListAccountsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(m, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

type AccountsListResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AccountsListResponse) Reset()         { *m = AccountsListResponse{} }
func (m *AccountsListResponse) String() string { return proto.CompactTextString(m) }
func (*AccountsListResponse) ProtoMessage()    {}
func (*AccountsListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *AccountsListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountsListResponse.Unmarshal(m, b)
}
func (m *AccountsListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountsListResponse.Marshal(b, m, deterministic)
}
func (m *AccountsListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountsListResponse.Merge(m, src)
}
func (m *AccountsListResponse) XXX_Size() int {
	return xxx_messageInfo_AccountsListResponse.Size(m)
}
func (m *AccountsListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountsListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountsListResponse proto.InternalMessageInfo

func (m *AccountsListResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type AuthenticateAccountRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateAccountRequest) Reset()         { *m = AuthenticateAccountRequest{} }
func (m *AuthenticateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateAccountRequest) ProtoMessage()    {}
func (*AuthenticateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *AuthenticateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateAccountRequest.Unmarshal(m, b)
}
func (m *AuthenticateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateAccountRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateAccountRequest.Merge(m, src)
}
func (m *AuthenticateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateAccountRequest.Size(m)
}
func (m *AuthenticateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateAccountRequest proto.InternalMessageInfo

func (m *AuthenticateAccountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthenticateAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticateAccountResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateAccountResponse) Reset()         { *m = AuthenticateAccountResponse{} }
func (m *AuthenticateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateAccountResponse) ProtoMessage()    {}
func (*AuthenticateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *AuthenticateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateAccountResponse.Unmarshal(m, b)
}
func (m *AuthenticateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateAccountResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateAccountResponse.Merge(m, src)
}
func (m *AuthenticateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateAccountResponse.Size(m)
}
func (m *AuthenticateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateAccountResponse proto.InternalMessageInfo

func (m *AuthenticateAccountResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ChangeAccountPasswordRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeAccountPasswordRequest) Reset()         { *m = ChangeAccountPasswordRequest{} }
func (m *ChangeAccountPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeAccountPasswordRequest) ProtoMessage()    {}
func (*ChangeAccountPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *ChangeAccountPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeAccountPasswordRequest.Unmarshal(m, b)
}
func (m *ChangeAccountPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeAccountPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangeAccountPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeAccountPasswordRequest.Merge(m, src)
}
func (m *ChangeAccountPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeAccountPasswordRequest.Size(m)
}
func (m *ChangeAccountPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeAccountPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeAccountPasswordRequest proto.InternalMessageInfo

func (m *ChangeAccountPasswordRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Project struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rules                []*Rule  `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	CreatedAt            int64    `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IssuesCount          int32    `protobuf:"varint,4,opt,name=issues_count,json=issuesCount,proto3" json:"issues_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *Project) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Project) GetIssuesCount() int32 {
	if m != nil {
		return m.IssuesCount
	}
	return 0
}

type Rule struct {
	MinAge int32 `protobuf:"varint,1,opt,name=min_age,json=minAge,proto3" json:"min_age,omitempty"`
	Count  int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// state (readonly)
	Files                []*File  `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	NextDate             int64    `protobuf:"varint,4,opt,name=next_date,json=nextDate,proto3" json:"next_date,omitempty"`
	Error                Error    `protobuf:"varint,5,opt,name=error,proto3,enum=Error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18}
}

func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (m *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(m, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetMinAge() int32 {
	if m != nil {
		return m.MinAge
	}
	return 0
}

func (m *Rule) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Rule) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *Rule) GetNextDate() int64 {
	if m != nil {
		return m.NextDate
	}
	return 0
}

func (m *Rule) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NO_ERROR
}

type File struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Date                 int64    `protobuf:"varint,2,opt,name=date,proto3" json:"date,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Expiration           int64    `protobuf:"varint,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Error                Error    `protobuf:"varint,5,opt,name=error,proto3,enum=Error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{19}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *File) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *File) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NO_ERROR
}

type Account struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterEnum("Error", Error_name, Error_value)
	proto.RegisterEnum("GetProjectsRequest_OrderBy", GetProjectsRequest_OrderBy_name, GetProjectsRequest_OrderBy_value)
	proto.RegisterEnum("GetProjectsRequest_OrderDirection", GetProjectsRequest_OrderDirection_name, GetProjectsRequest_OrderDirection_value)
	proto.RegisterType((*GetProjectsRequest)(nil), "GetProjectsRequest")
	proto.RegisterType((*ProjectsListResponse)(nil), "ProjectsListResponse")
	proto.RegisterType((*CreateProjectRequest)(nil), "CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "CreateProjectResponse")
	proto.RegisterType((*GetProjectRequest)(nil), "GetProjectRequest")
	proto.RegisterType((*ProjectResponse)(nil), "ProjectResponse")
	proto.RegisterType((*GetFilesRequest)(nil), "GetFilesRequest")
	proto.RegisterType((*GetFilesResponse)(nil), "GetFilesResponse")
	proto.RegisterType((*GetFileURLRequest)(nil), "GetFileURLRequest")
	proto.RegisterType((*GetFileURLResponse)(nil), "GetFileURLResponse")
	proto.RegisterType((*CreateAccountRequest)(nil), "CreateAccountRequest")
	proto.RegisterType((*AccountResponse)(nil), "AccountResponse")
	proto.RegisterType((*ListAccountsRequest)(nil), "ListAccountsRequest")
	proto.RegisterType((*AccountsListResponse)(nil), "AccountsListResponse")
	proto.RegisterType((*AuthenticateAccountRequest)(nil), "AuthenticateAccountRequest")
	proto.RegisterType((*AuthenticateAccountResponse)(nil), "AuthenticateAccountResponse")
	proto.RegisterType((*ChangeAccountPasswordRequest)(nil), "ChangeAccountPasswordRequest")
	proto.RegisterType((*Project)(nil), "Project")
	proto.RegisterType((*Rule)(nil), "Rule")
	proto.RegisterType((*File)(nil), "File")
	proto.RegisterType((*Account)(nil), "Account")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 928 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0x93, 0xb8, 0x71, 0x4e, 0xda, 0xad, 0x3b, 0x4d, 0x20, 0x72, 0xba, 0xa8, 0x0c, 0x7f,
	0x15, 0x17, 0x53, 0x29, 0xab, 0x45, 0x0b, 0x8b, 0x40, 0x6e, 0xe2, 0x2d, 0x85, 0xac, 0x5d, 0x26,
	0xa9, 0x90, 0xb8, 0xb1, 0xbc, 0xc9, 0xd0, 0x9a, 0x4d, 0xed, 0x60, 0x4f, 0xc4, 0x2e, 0xe2, 0x82,
	0x17, 0xe0, 0x6d, 0x78, 0x2c, 0x1e, 0x02, 0xcd, 0x78, 0xec, 0xa4, 0x89, 0x5b, 0x28, 0x57, 0x9d,
	0xf9, 0xce, 0x39, 0xdf, 0xf9, 0x99, 0xe3, 0x2f, 0x85, 0x46, 0x30, 0x0f, 0xc9, 0x3c, 0x89, 0x79,
	0x8c, 0xff, 0xd6, 0x00, 0x9d, 0x31, 0x7e, 0x91, 0xc4, 0x3f, 0xb3, 0x09, 0x4f, 0x29, 0xfb, 0x65,
	0xc1, 0x52, 0x8e, 0x3e, 0x03, 0x23, 0x4e, 0xa6, 0x2c, 0xf1, 0x5f, 0xbd, 0xed, 0x68, 0x47, 0xda,
	0xf1, 0xa3, 0x5e, 0x97, 0x6c, 0xba, 0x11, 0x4f, 0xf8, 0x9c, 0xbe, 0xa5, 0xf5, 0x38, 0x3b, 0xa0,
	0xaf, 0xa1, 0x91, 0xc5, 0x4d, 0xc3, 0xa4, 0x53, 0x91, 0x81, 0xf8, 0xce, 0xc0, 0x41, 0x98, 0xb0,
	0x09, 0x0f, 0xe3, 0x88, 0x66, 0xc9, 0x06, 0x61, 0x82, 0x9f, 0x41, 0x5d, 0x91, 0x22, 0x03, 0x6a,
	0xae, 0xfd, 0xd2, 0x31, 0xb7, 0xd0, 0x3e, 0xec, 0xf6, 0xa9, 0x63, 0x8f, 0xcf, 0x3d, 0xd7, 0x1f,
	0xd8, 0x63, 0xc7, 0xd4, 0x90, 0x09, 0x3b, 0xe7, 0xa3, 0xd1, 0xa5, 0x33, 0xf2, 0xfb, 0xde, 0xa5,
	0x3b, 0x36, 0x2b, 0xf8, 0x03, 0x78, 0x74, 0x9b, 0x15, 0xd5, 0xa1, 0x6a, 0x8f, 0xfa, 0xe6, 0x96,
	0x60, 0x1a, 0x38, 0xa3, 0xbe, 0xa9, 0x61, 0x0a, 0xad, 0xbc, 0x94, 0x61, 0x98, 0x72, 0xca, 0xd2,
	0x79, 0x1c, 0xa5, 0x0c, 0x7d, 0x08, 0xc6, 0x5c, 0xe1, 0x1d, 0xed, 0xa8, 0x7a, 0xdc, 0xec, 0x19,
	0x44, 0x39, 0xd2, 0xc2, 0x82, 0x5a, 0xa0, 0xf3, 0x98, 0x07, 0x33, 0xd9, 0x99, 0x4e, 0xb3, 0x0b,
	0x3e, 0x83, 0x56, 0x3f, 0x61, 0x01, 0x67, 0x79, 0x80, 0x9a, 0x21, 0x82, 0x5a, 0x14, 0xdc, 0x30,
	0x39, 0xbf, 0x06, 0x95, 0x67, 0xd4, 0x05, 0x3d, 0x59, 0xcc, 0x58, 0xda, 0xa9, 0xc8, 0x24, 0x3a,
	0xa1, 0x8b, 0x19, 0xa3, 0x19, 0x86, 0x9f, 0x43, 0x7b, 0x8d, 0x48, 0x55, 0x87, 0xa1, 0xae, 0x6a,
	0x90, 0x64, 0xab, 0xc5, 0xe5, 0x06, 0xfc, 0x09, 0xec, 0x2f, 0xe7, 0x7c, 0x4f, 0x09, 0xf8, 0x29,
	0xec, 0xfd, 0x1f, 0xfe, 0x6f, 0x61, 0xef, 0x8c, 0xf1, 0x17, 0xe1, 0x8c, 0x15, 0x4b, 0xf2, 0x3e,
	0xec, 0x28, 0xab, 0xbf, 0x92, 0xa5, 0xa9, 0x30, 0x57, 0xf4, 0xdb, 0x02, 0x7d, 0x16, 0xde, 0x84,
	0x3c, 0x9f, 0x98, 0xbc, 0xe0, 0x13, 0x30, 0x97, 0x5c, 0xaa, 0x86, 0x2e, 0xe8, 0x3f, 0x09, 0x40,
	0x8d, 0x5f, 0x27, 0xc2, 0x4c, 0x33, 0x0c, 0x9f, 0xc8, 0xe6, 0x04, 0x72, 0x49, 0x87, 0x79, 0x7a,
	0x0b, 0x0c, 0x61, 0x9d, 0x07, 0xfc, 0x5a, 0xa5, 0x2e, 0xee, 0xf8, 0x63, 0xb9, 0xd5, 0x45, 0x80,
	0xca, 0x61, 0x42, 0x75, 0x91, 0xcc, 0x94, 0xb3, 0x38, 0xe2, 0x5e, 0xfe, 0x76, 0xf6, 0x64, 0x12,
	0x2f, 0x22, 0xbe, 0xc2, 0xbd, 0x48, 0x59, 0xb2, 0xd2, 0x56, 0x71, 0xc7, 0xdf, 0xc3, 0x5e, 0xe1,
	0xbd, 0x1c, 0x60, 0x90, 0x41, 0xc5, 0x00, 0x73, 0x97, 0xdc, 0x20, 0x28, 0xe7, 0x41, 0x9a, 0xfe,
	0x1a, 0x27, 0x53, 0x39, 0x8d, 0x06, 0x2d, 0xee, 0xb8, 0x0d, 0x07, 0x62, 0x1d, 0x55, 0x4c, 0x3e,
	0x60, 0xfc, 0x25, 0xb4, 0x72, 0x68, 0x7d, 0x5b, 0x15, 0xeb, 0x72, 0x5b, 0xf3, 0x7c, 0x85, 0x05,
	0x8f, 0xc1, 0xb2, 0x17, 0xfc, 0x9a, 0x45, 0x3c, 0x9c, 0x3c, 0xa8, 0xc3, 0x7b, 0x4b, 0x7d, 0x02,
	0xdd, 0x52, 0x56, 0x55, 0x9a, 0xfc, 0x44, 0x5e, 0xb3, 0x48, 0x71, 0x66, 0x17, 0xfc, 0x05, 0x1c,
	0xf6, 0xaf, 0x83, 0xe8, 0x2a, 0x77, 0xbf, 0x50, 0x6c, 0xff, 0x65, 0xdc, 0xbf, 0x43, 0x5d, 0x2d,
	0xe3, 0x83, 0xbf, 0x28, 0xf4, 0x18, 0x60, 0x22, 0x9f, 0x77, 0xea, 0x07, 0xbc, 0x53, 0x3d, 0xd2,
	0x8e, 0xab, 0xb4, 0xa1, 0x10, 0x5b, 0x2e, 0x70, 0x98, 0xa6, 0x0b, 0x96, 0xfa, 0xd9, 0xdb, 0xd5,
	0xe4, 0x92, 0x36, 0x33, 0xac, 0x2f, 0x20, 0xfc, 0xa7, 0x06, 0x35, 0xc1, 0x88, 0xde, 0x85, 0xfa,
	0x4d, 0x18, 0xf9, 0xc1, 0x55, 0x96, 0x5e, 0xa7, 0xdb, 0x37, 0x61, 0x64, 0x5f, 0xc9, 0x8e, 0xb3,
	0x68, 0xb5, 0xe2, 0xd9, 0x6b, 0x17, 0xeb, 0x5c, 0xdd, 0x5c, 0x67, 0xd4, 0x85, 0x46, 0xc4, 0xde,
	0x70, 0x7f, 0x1a, 0x70, 0x26, 0x93, 0x56, 0xa9, 0x21, 0x80, 0x41, 0xc0, 0x19, 0x3a, 0x04, 0x9d,
	0x25, 0x49, 0x9c, 0x74, 0x74, 0x29, 0x9f, 0xdb, 0xc4, 0x11, 0x37, 0x9a, 0x81, 0xf8, 0x0f, 0x0d,
	0x6a, 0x82, 0x4a, 0xcc, 0x62, 0x65, 0xf3, 0xe5, 0x59, 0x60, 0x92, 0xb2, 0x22, 0x29, 0xe5, 0x59,
	0x60, 0x69, 0xf8, 0x1b, 0x53, 0xcd, 0xcb, 0x33, 0x7a, 0x0f, 0x80, 0xbd, 0x99, 0x87, 0x49, 0x20,
	0x64, 0x52, 0x15, 0xb0, 0x82, 0xfc, 0x4b, 0x09, 0x1f, 0x41, 0xdd, 0x5e, 0xee, 0xf4, 0x5d, 0xef,
	0xf6, 0xe9, 0x10, 0x74, 0x19, 0x86, 0x76, 0xc0, 0x70, 0x3d, 0xdf, 0xa1, 0xd4, 0xa3, 0xe6, 0x16,
	0x6a, 0x42, 0xfd, 0xd2, 0xfd, 0xce, 0xf5, 0x7e, 0x70, 0x4d, 0x4d, 0x98, 0xbc, 0xd3, 0x91, 0x37,
	0x74, 0xc6, 0x8e, 0x59, 0x41, 0xbb, 0xd0, 0x18, 0x7b, 0x9e, 0x3f, 0x7a, 0x69, 0x0f, 0x87, 0x66,
	0x55, 0x78, 0xba, 0x9e, 0xff, 0xe2, 0x7c, 0xe8, 0x98, 0xb5, 0xde, 0x5f, 0x35, 0x30, 0x4e, 0x83,
	0xc9, 0xeb, 0xc4, 0x9e, 0x87, 0xe8, 0x73, 0x68, 0xae, 0xfc, 0xa6, 0xa0, 0x83, 0x92, 0x5f, 0x18,
	0xab, 0x4d, 0x4a, 0x85, 0xbe, 0x07, 0xb0, 0x74, 0x46, 0x88, 0x6c, 0x68, 0xa6, 0x65, 0x92, 0x75,
	0x79, 0xfc, 0x0a, 0x76, 0x6f, 0xe9, 0x32, 0x6a, 0x93, 0x32, 0xc1, 0xb7, 0xde, 0x21, 0xe5, 0xf2,
	0x7d, 0x02, 0x46, 0x2e, 0x77, 0xc8, 0x24, 0x6b, 0x2a, 0x6a, 0xed, 0x93, 0x0d, 0x2d, 0x7c, 0x2a,
	0x8b, 0x54, 0xea, 0x95, 0x15, 0x79, 0x5b, 0xfb, 0xac, 0x03, 0x52, 0x22, 0x6f, 0xcf, 0xf2, 0x3a,
	0xf3, 0xe7, 0xc9, 0xeb, 0xbc, 0xfd, 0xe9, 0x5b, 0x26, 0x59, 0xff, 0x6a, 0x9f, 0xc3, 0xce, 0xaa,
	0xfe, 0xa0, 0x16, 0x29, 0x91, 0x23, 0xab, 0x4d, 0x4a, 0xd5, 0xe8, 0x02, 0x0e, 0x4a, 0x14, 0x01,
	0x75, 0xc9, 0xdd, 0xea, 0x63, 0x1d, 0x92, 0xfb, 0x44, 0xe4, 0x1b, 0x68, 0x97, 0xca, 0x05, 0x7a,
	0x4c, 0xee, 0x93, 0x91, 0xcd, 0xc6, 0x4e, 0xeb, 0x3f, 0xea, 0xf2, 0xff, 0x9c, 0x57, 0xdb, 0xf2,
	0xcf, 0x93, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x46, 0xd6, 0xe0, 0x3d, 0xfb, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BackrApiClient is the client API for BackrApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BackrApiClient interface {
	// projects
	GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*ProjectsListResponse, error)
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	// files
	GetFiles(ctx context.Context, in *GetFilesRequest, opts ...grpc.CallOption) (*GetFilesResponse, error)
	GetFileURL(ctx context.Context, in *GetFileURLRequest, opts ...grpc.CallOption) (*GetFileURLResponse, error)
	// account
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*AccountsListResponse, error)
	AuthenticateAccount(ctx context.Context, in *AuthenticateAccountRequest, opts ...grpc.CallOption) (*AuthenticateAccountResponse, error)
	ChangeAccountPassword(ctx context.Context, in *ChangeAccountPasswordRequest, opts ...grpc.CallOption) (*AccountResponse, error)
}

type backrApiClient struct {
	cc *grpc.ClientConn
}

func NewBackrApiClient(cc *grpc.ClientConn) BackrApiClient {
	return &backrApiClient{cc}
}

func (c *backrApiClient) GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*ProjectsListResponse, error) {
	out := new(ProjectsListResponse)
	err := c.cc.Invoke(ctx, "/BackrApi/GetProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backrApiClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	out := new(ProjectResponse)
	err := c.cc.Invoke(ctx, "/BackrApi/GetProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backrApiClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	out := new(CreateProjectResponse)
	err := c.cc.Invoke(ctx, "/BackrApi/CreateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backrApiClient) GetFiles(ctx context.Context, in *GetFilesRequest, opts ...grpc.CallOption) (*GetFilesResponse, error) {
	out := new(GetFilesResponse)
	err := c.cc.Invoke(ctx, "/BackrApi/GetFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backrApiClient) GetFileURL(ctx context.Context, in *GetFileURLRequest, opts ...grpc.CallOption) (*GetFileURLResponse, error) {
	out := new(GetFileURLResponse)
	err := c.cc.Invoke(ctx, "/BackrApi/GetFileURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backrApiClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, "/BackrApi/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backrApiClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*AccountsListResponse, error) {
	out := new(AccountsListResponse)
	err := c.cc.Invoke(ctx, "/BackrApi/ListAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backrApiClient) AuthenticateAccount(ctx context.Context, in *AuthenticateAccountRequest, opts ...grpc.CallOption) (*AuthenticateAccountResponse, error) {
	out := new(AuthenticateAccountResponse)
	err := c.cc.Invoke(ctx, "/BackrApi/AuthenticateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backrApiClient) ChangeAccountPassword(ctx context.Context, in *ChangeAccountPasswordRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, "/BackrApi/ChangeAccountPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackrApiServer is the server API for BackrApi service.
type BackrApiServer interface {
	// projects
	GetProjects(context.Context, *GetProjectsRequest) (*ProjectsListResponse, error)
	GetProject(context.Context, *GetProjectRequest) (*ProjectResponse, error)
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	// files
	GetFiles(context.Context, *GetFilesRequest) (*GetFilesResponse, error)
	GetFileURL(context.Context, *GetFileURLRequest) (*GetFileURLResponse, error)
	// account
	CreateAccount(context.Context, *CreateAccountRequest) (*AccountResponse, error)
	ListAccounts(context.Context, *ListAccountsRequest) (*AccountsListResponse, error)
	AuthenticateAccount(context.Context, *AuthenticateAccountRequest) (*AuthenticateAccountResponse, error)
	ChangeAccountPassword(context.Context, *ChangeAccountPasswordRequest) (*AccountResponse, error)
}

// UnimplementedBackrApiServer can be embedded to have forward compatible implementations.
type UnimplementedBackrApiServer struct {
}

func (*UnimplementedBackrApiServer) GetProjects(ctx context.Context, req *GetProjectsRequest) (*ProjectsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjects not implemented")
}
func (*UnimplementedBackrApiServer) GetProject(ctx context.Context, req *GetProjectRequest) (*ProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProject not implemented")
}
func (*UnimplementedBackrApiServer) CreateProject(ctx context.Context, req *CreateProjectRequest) (*CreateProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (*UnimplementedBackrApiServer) GetFiles(ctx context.Context, req *GetFilesRequest) (*GetFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFiles not implemented")
}
func (*UnimplementedBackrApiServer) GetFileURL(ctx context.Context, req *GetFileURLRequest) (*GetFileURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileURL not implemented")
}
func (*UnimplementedBackrApiServer) CreateAccount(ctx context.Context, req *CreateAccountRequest) (*AccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (*UnimplementedBackrApiServer) ListAccounts(ctx context.Context, req *ListAccountsRequest) (*AccountsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccounts not implemented")
}
func (*UnimplementedBackrApiServer) AuthenticateAccount(ctx context.Context, req *AuthenticateAccountRequest) (*AuthenticateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateAccount not implemented")
}
func (*UnimplementedBackrApiServer) ChangeAccountPassword(ctx context.Context, req *ChangeAccountPasswordRequest) (*AccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeAccountPassword not implemented")
}

func RegisterBackrApiServer(s *grpc.Server, srv BackrApiServer) {
	s.RegisterService(&_BackrApi_serviceDesc, srv)
}

func _BackrApi_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackrApiServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackrApi/GetProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackrApiServer).GetProjects(ctx, req.(*GetProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackrApi_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackrApiServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackrApi/GetProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackrApiServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackrApi_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackrApiServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackrApi/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackrApiServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackrApi_GetFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackrApiServer).GetFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackrApi/GetFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackrApiServer).GetFiles(ctx, req.(*GetFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackrApi_GetFileURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackrApiServer).GetFileURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackrApi/GetFileURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackrApiServer).GetFileURL(ctx, req.(*GetFileURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackrApi_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackrApiServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackrApi/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackrApiServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackrApi_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackrApiServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackrApi/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackrApiServer).ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackrApi_AuthenticateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackrApiServer).AuthenticateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackrApi/AuthenticateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackrApiServer).AuthenticateAccount(ctx, req.(*AuthenticateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackrApi_ChangeAccountPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeAccountPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackrApiServer).ChangeAccountPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackrApi/ChangeAccountPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackrApiServer).ChangeAccountPassword(ctx, req.(*ChangeAccountPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BackrApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BackrApi",
	HandlerType: (*BackrApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProjects",
			Handler:    _BackrApi_GetProjects_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _BackrApi_GetProject_Handler,
		},
		{
			MethodName: "CreateProject",
			Handler:    _BackrApi_CreateProject_Handler,
		},
		{
			MethodName: "GetFiles",
			Handler:    _BackrApi_GetFiles_Handler,
		},
		{
			MethodName: "GetFileURL",
			Handler:    _BackrApi_GetFileURL_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _BackrApi_CreateAccount_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _BackrApi_ListAccounts_Handler,
		},
		{
			MethodName: "AuthenticateAccount",
			Handler:    _BackrApi_AuthenticateAccount_Handler,
		},
		{
			MethodName: "ChangeAccountPassword",
			Handler:    _BackrApi_ChangeAccountPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
