[s3]
bucket =  "backr"
endpoint =  "localhost:9001"
access_key =  "backr-test"
secret_key =  "backr-test"
region = ""
use_tls =  false

[bolt]
filepath = "bolt.db"

[api]
listen_ip = "127.0.0.1"
listen_port = "3000"
jwt_secret = "a_very_secure_key"